### ISSUE TITLE
Horizontal scrolling in any state but open

### ISSUE THREAD

**Issue by cookeri6** [mkko/DrawerView#12]
It seems that in the most recent version of your code, the ability to horizontally scroll when the DrawerView is in any other position but open does not work.

I noticed that this functionality is part of your demo app, but it does not function outside of your demo app.

**Comment by cookeri6** [comment]
When I manually include the relevant classes for DrawerView in my code, horizontal scroll works 🤨

**Comment by cookeri6** [comment]
The issue was that there hasn't been a release tag cut for a while.

**Comment by mkko** [comment]
Thanks for reminding me, I'll push out a new version soon. I just haven't had the time to check for any breaking changes.

**Comment by DhavalBhimani** [comment]
@mkko @cookeri6 any update on this? i am facing the similar issue. when drawer is partially opened. collectionview inside it is not scrolling.

**Comment by mkko** [comment]
@DhavalBhimani If I remember correctly, the subview scroll should be disabled if drawer is not fully expanded. Is this your case?

There's also an issue with horizontal scrolling being troublesome, drawer picks too easily the pan and starts moving. I simply haven't had the time to add better support for horizontal scroll yet, apologies for that.

**Comment by KesWalker** [comment]
Hello @mkko , don't suppose 5 years later you've had any time to add better support for horizontal scrolling? 😅

**Comment by mkko** [comment]
@KesWalker, I'd be interested to understand which way to make it better. I've used horizontal scrolling when paging and I think that works okayish. The challenge is not really a technical but usability, like when should the drawer highjack the scrolling or how should the scrolling work in general if orientation lock is not used.

EDIT: I just read my previous comment here. However, I'm not sure if this is still valid or not. In my personal projects the horizontal scrolling works fine. If you could provide a simple app to demonstrate this, I could try to see what the issue is.
