### ISSUE TITLE
Collection behaves buggy when I am adding as a subview

### ISSUE THREAD

**Issue by developweb10** [mkko/DrawerView#20]
Hi, 
First of all, thank you for providing us a great tool, here is the issue I am facing when I am adding a Horizontal collection view as a subview of a drawer view When I am trying to scroll the collection view drawer gets changed its states.

**Comment by kuchmiyalex** [comment]
Hi, getting same issue, it's getting very hard to perform horizontal swipes

**Comment by cjwillis809** [comment]
@mkko My team is seeing this same issue as well. We added a collection view as a subview to the drawer and it's very hard to scroll without triggering the drawer's gesture recognizer it seems. Have you gotten a chance to look at this?

**Comment by mkko** [comment]
Sorry, I haven't had the time yet. Do you have a working example of the issue? Would save a lot of time.

**Comment by mkko** [comment]
@developweb10 / @kuchmiyalex / @cjwillis809, I pushed version 1.3.1 with a minor fix to issue where at the end of a pan the horizontal lock was not regarded due to vertical velocity. In other words, sometimes the drawer got collapsed when there was enough vertical movement (despite the directional lock).

Does this address your issue? I still haven't had the time to try the drawer with collection view, so if the problem persists, I could look at some of your sample to determine the issue better.

**Comment by developweb10** [comment]
@mkko , Yes it is working correctly when I update the pod 1.3.1... Thanks for providing me a solution...
