### ISSUE TITLE
Make DrawerView extensible

### ISSUE THREAD

**Issue by decanus** [mkko/DrawerView#36]
Any chance you could make the `DrawerView` class `open` this would allow extending it and setting up the view within a subclass itself.

**Comment by mkko** [comment]
Hi! I really don't see why not, but just out of curiosity, how'd you like to extend it?

**Comment by decanus** [comment]
I'd like to have almost a viewDidLoad like function where I could setup the contents of the drawer, this allows a nicer compartmentalized drawerview rather than having to do that all in the view controller.

**Comment by wyszo** [comment]
Hi! 

While there is nothing wrong with making the DrawerView class open, this specific use case is already handled in a better way by the library. 

The problem you're describing should not be solved by inheritance if possible. 

When the DrawerView is being initialised, all it needs is it's content view. That already guarantees the compartmentalisation you're talking about: the code to set the drawer up is separate from the code that creates the content view (or rather it's ViewController). 

See the repository code (particularly the `Extensions.swift` file and `DrawerViewExample`) to see how to best achieve that. 

Here's an easy to digest explanation of inheritance vs composition (and why the latter is preferred): https://softwareengineering.stackexchange.com/a/371715

**Comment by mkko** [comment]
If there's a good reason, I'd gladly make DrawerView open class. However, doing that just to make it extensible in general makes things easy to break due to some change in the DrawerView.

As for the initialisation process, I'd gladly improve it since the whole setup might not be the easiest to communicate. For any specific questions, please open a new issue and I'll try to help. I'll close this for now.
